destination: ./_site
safe:        true
auto:        true
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   /articles/:title
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex
exclude: ./design
